"""add_student_photo_table

Revision ID: 3d90e9f4d763
Revises: c5bdd3e50b66
Create Date: 2025-09-17 17:42:08.338027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d90e9f4d763'
down_revision: Union[str, Sequence[str], None] = 'c5bdd3e50b66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students_photos',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('student_id', sa.BIGINT(), nullable=False, foreign_key='students.id'),
    sa.Column('file_path', sa.TEXT(), nullable=True),
    sa.Column('file_name', sa.TEXT(), nullable=True),
    sa.Column('photo_quality', sa.Enum('EXCELLENT', 'GOOD', 'FAIR', 'POOR', name='photoquality'), nullable=True),
    sa.Column('face_detected', sa.BOOLEAN(), nullable=False),
    sa.Column('face_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_photos_student_id'), 'students_photos', ['student_id'], unique=False)
    op.drop_column('students', 'photo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('photo_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_photos_student_id'), table_name='students_photos')
    op.drop_table('students_photos')
    op.execute("DROP TYPE IF EXISTS photoquality")
    # ### end Alembic commands ###
